version: '3.8'

services:
  merchStore:
    container_name: merchStoreDB
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=merchDatabase'
      - 'POSTGRES_PASSWORD=u#OE9cQVA@7iR&iv'
      - 'POSTGRES_USER=ToJestTrudnyLogin'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - '15432:80'
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - merchStore

volumes:
  postgres_data:
